### ISSUE TITLE
作者可以把demo上传上来吗？

### ISSUE THREAD

**Issue by klaus-pd** [vindell/spring-boot-starter-shiro-biz#1]
@vindell

**Comment by hiwepy** [comment]
因为开发工作比较忙，没有单独抽取使用demo,你可以参考这个地址：[https://github.com/Jeebiz/jeebiz-boot/tree/master/jeebiz-boot-samples](https://github.com/Jeebiz/jeebiz-boot/tree/master/jeebiz-boot-samples) 里面是一些应用实例，有用到这个组件
